package com.example.eksamensprojektsbilapp.Model;

import java.sql.Date;

public class RentalAgreement {
    private int rentalAgreementID; // not a part of the constructor. Needs to be defined manually after getting the ID generated by MySQL.
    private int customerID;
    private String vinNumber;
    private double price;
    private Date rentalStartdate;
    private Date rentalEndDate;


    public RentalAgreement(int customerID, String vinNumber, double price, Date rentalStartdate, Date rentalEndDate) {
        this.customerID = customerID;
        this.vinNumber = vinNumber;
        this.price = price;
        this.rentalStartdate = rentalStartdate;
        this.rentalEndDate = rentalEndDate;
    }

    public int getRentalAgreementID() {
        return rentalAgreementID;
    }

    public void setRentalAgreementID(int rentalAgreementID) {
        this.rentalAgreementID = rentalAgreementID;
    }

    public int getCustomerID() {
        return customerID;
    }

    public void setCustomerID(int customerID) {
        this.customerID = customerID;
    }

    public String getVinNumber() {
        return vinNumber;
    }

    public void setVinNumber(String vinNumber) {
        this.vinNumber = vinNumber;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public Date getRentalStartdate() {
        return rentalStartdate;
    }

    public void setRentalStartdate(Date rentalStartdate) {
        this.rentalStartdate = rentalStartdate;
    }

    public Date getRentalEndDate() {
        return rentalEndDate;
    }

    public void setRentalEndDate(Date rentalEndDate) {
        this.rentalEndDate = rentalEndDate;
    }


}
